// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl5bZ5XAiZjYDqgfsp2HrzFVDTSMXr5sU',
    appId: '1:691214977057:web:457dd84179649872a03b60',
    messagingSenderId: '691214977057',
    projectId: 'nishamnotes-88afe',
    authDomain: 'nishamnotes-88afe.firebaseapp.com',
    storageBucket: 'nishamnotes-88afe.appspot.com',
    measurementId: 'G-YZFTKXB593',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU6g435ElTYZvOWOGFtGeS46-xVXWGWtQ',
    appId: '1:691214977057:android:a53e2b279c809a56a03b60',
    messagingSenderId: '691214977057',
    projectId: 'nishamnotes-88afe',
    storageBucket: 'nishamnotes-88afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9tW83DJidauElzYKcEdJMw33-jjOXe9c',
    appId: '1:691214977057:ios:e44d1008423032c9a03b60',
    messagingSenderId: '691214977057',
    projectId: 'nishamnotes-88afe',
    storageBucket: 'nishamnotes-88afe.appspot.com',
    iosClientId: '691214977057-9enonrtj4srgp81a3smqceme4ousen3v.apps.googleusercontent.com',
    iosBundleId: 'np.com.nishamghimire.nishamnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9tW83DJidauElzYKcEdJMw33-jjOXe9c',
    appId: '1:691214977057:ios:2d161c7e6d4f7042a03b60',
    messagingSenderId: '691214977057',
    projectId: 'nishamnotes-88afe',
    storageBucket: 'nishamnotes-88afe.appspot.com',
    iosClientId: '691214977057-0tlf3tb91q0slbn3rm3698t170lloi1i.apps.googleusercontent.com',
    iosBundleId: 'np.com.nishamghimire.nishamnotes.RunnerTests',
  );
}
